language: csharp
env:
  - PROJECT=CS-Successful  
  - PROJECT=NUnit-CS-Success
  
solution: $PROJECT/$PROJECT.sln
install:
  - nuget restore $PROJECT/$PROJECT.sln
  - nuget install NUnit.Runners -Version 3.2.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug $PROJECT/$PROJECT.sln
  - chmod +x ./run-tests.sh 
  - ./run-tests.sh $PROJECT

