language: csharp
env:
  - PROJECT=CS-Successful
  - PROJECT=CS-Failed
  - PROJECT=NUnit-CS-Success
  
solution: $PROJECT/$PROJECT.sln
install:
  - nuget restore $PROJECT/$PROJECT.sln
  - nuget install NUnit.Runners -Version 3.2.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug $PROJECT/$PROJECT.sln
  - mono ./testrunner/NUnit.Runners.3.2.0/tools/nunit-console.exe ./$PROJECT/bin/Debug/$PROJECT.exe

